
name: Add issue to project
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  backlog:
    runs-on: ubuntu-latest
    steps:
      - uses: kreemer/backlog-action@main
        with:
          owner: kreemer
          number: 1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: verify
          label-color: 0E8A16
          label-description: Identifies all tasks which should be scrutinized